server:
  port: 8081

spring:
  application:
    name: identity-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cpas_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  security:
    keys-path: ../keys
    jwt-issuer: ${JWT_ISSUER:identity-service}
    jwt-expires-in-hours: ${JWT_EXPIRES_IN_HOURS:8}
